/*Last M Digit Generate-able
A number ‘f’ is said to be generatable if it can be generated in a Fibonacci-like sequence from its digits. Initially the sequence contains the digits in it from left to right and the next number in the sequence is generated by summing up the last ‘d’ numbers in the sequence where ‘d’ is the number of digits in ‘f’. For example, the number 197 can be got in a sequence 1, 9, 7, 17, 33, 57, 107, 197 by adding last three numbers.

A number ‘n’ is said to be last ‘m’ digit generate-able if the number that can be formed with last ‘m’ digits of it can be generated from them. For example 23197 is last 3 digit generate-able, 371104 is last 4 digit generate-able, 17844121607 is last 8 digit generate-able.

Input Format

First line contains the number n

Next line contains the number of last digits m

Output Format

Print either Generated or Cannot be generated*/
#include<stdio.h>
#include<math.h>
int generate(long int n, int m)
{
    int a[m],i=0,sum,new_no=0,r,flag=0;
    while(i<m)
      {
        r=n%10;
        new_no+=r*pow(10,i);
        a[m-i-1]=r;
        i++;
        n=n/10;
      }
  while(sum<new_no)
    {
        sum=0;
        for(i=0;i<m;i++)
        {
            sum+=a[i];
        }
        for(i=0;i<m-1;i++)
        {
            a[i]=a[i+1];
        }
        a[m-1]=sum;
        if(sum==new_no)
        {
            flag=1;
            break;
        }

    }
if(flag==0)
  return 0;
else 
  return 1;
}
int main()
{
    long int n;
    int m,num;
    scanf("%ld",&n);
    scanf("%d",&m);
    if(generate(n,m)==0)
      printf("Cannot be generated");
    else
      printf("Generated");
   
}
